version: '3'

networks:
  my-network:

services:
  app:
    image: node:18.15.0
    user: "node"
    working_dir: /app
    environment:
      - NPM_CONFIG_PREFIX=/home/node/.npm-global=value
      - PATH=$PATH:/home/node/.npm-global/bin
    volumes:
      - ./:/app
    depends_on:
      - neo4j
    ports:
      - 8080:8080
    networks:
      - my-network
    command: bash run.sh

  neo4j:
    image: neo4j:5.6.0
    hostname: neo4j
    environment:
      dbms.connectors.default_listen_address: 0.0.0.0
      dbms.connector.http.enabled: "true"
      dbms.connector.bolt.enabled: "true"
      apoc.export.file.enabled: "true"
      apoc.import.file.enabled: "true"
      apoc.import.file.use_neo4j_config: "true"
      NEO4J_PLUGINS: "apoc"
      NEO4J_AUTH: neo4j/password
    volumes:
      - '${APOC}:/plugins'
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - my-network
